(import (scheme base)
        (scheme write)
        (test unit-test)
        (maclisp))

(test (eq 1 1) #t)
(test (eq 1 2) #f)
(test (let ((v 0)) (aset' v 123) v) 123)
(test (explode 'hello) '(h e l l o))
(test (implode '(h e l l o)) 'hello)
(test (implode (cdr (explode 'hello))) 'ello)
(test (numberp 123) #t)
(test (numberp 'abc) #f)
(test (exploden 'abba) '(97 98 98 97))
