(import (scheme base)
        (scheme write))

(display "Expect (() . 1)")
(newline)
(display "       ")
(display (cons '() 1))
(newline)
(newline)

(display "Expect (() () ())")
(newline)
(display "       ")
(display (list '() '() '()))
(newline)
(newline)

(display "Expect (() ())")
(newline)
(display "       ")
(display (list '() '()))
(newline)
(newline)

(display "Expect (() () ())")
(newline)
(display "       ")
(display (list '() '() '()))
(newline)
(newline)

(display "Expect (())")
(newline)
(display "       ")
(display (list '()))
(newline)
(newline)

(display "Expect (1)")
(newline)
(display "       ")
(display (cons 1 '()))
(newline)
(newline)

(display "Expect (2 1)")
(newline)
(display "       ")
(display (cons 2 (cons 1 '())))
(newline)
(newline)

(display "Expect (())")
(newline)
(display "       ")
(display (cons '() '()))
(newline)
(newline)

(display "Expect (())")
(newline)
(display "       ")
(display (list '()))
(newline)
(newline)

